modLoader="javafml"
loaderVersion="[52,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/vfx-dev/Somnia-Awoken-CE/issues"
showAsResourcePack=false
clientSideOnly=false

[[mods]]
modId="somnia"
version="${version}"
displayName="Somnia Awoken: Community Edition"
displayURL="https://github.com/vfx-dev/Somnia-Awoken-CE"
logoFile="logo.png"
credits="MALfunction84, Kingrunes, Su5eD, authors of previous versions"
authors="FalsePattern"
description="Simulating the world while you sleep"
[[dependencies.somnia]]
    modId="forge"
    mandatory=true
    versionRange="[52.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
