modLoader="javafml"
loaderVersion="[1,)"
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/vfx-dev/Somnia-Awoken-CE/issues"

[[mods]]
modId="somnia"
version="${version}"
displayName="Somnia Awoken: Community Edition"
displayURL="https://github.com/vfx-dev/Somnia-Awoken-CE"
logoFile="logo.png"
credits="MALfunction84, Kingrunes, Su5eD, authors of previous versions"
authors="FalsePattern"
description="Simulating the world while you sleep"

[[dependencies.somnia]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.somnia]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
